package org.example.backend.Enums;

public enum Specialization {
    IT_SYSTEMS , IT_HELP_DESK , INFRASTRUCTURE, NETWORKING, SECURITY, DATABASE_ADMINISTRATION, SOFTWARE_DEVELOPMENT, CLOUD_SERVICES, TECHNICAL_SUPPORT, DATA_ANALYSIS
}
